<?php

namespace Oro\Bundle\IssueBundle\Entity\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getIssuesOfUser($userId)
    {
        return $this->createQueryBuilder('issue')
            ->where('issue.reporter = :userId OR issue.assignee = :userId')
            ->orderBy('issue.createdAt', 'DESC')
            ->setFirstResult(0)
          //  ->setMaxResults($limit)
            ->setParameter('userId', $userId)
            ->getQuery()
            ->execute();
    }
}
