oro_issue_bundle:
    resource:     "@OroIssueBundle/Controller"
    type:         annotation
    prefix:       /issue

oro_issue_dashboard:
    resource:     "@OroIssueBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard

oro_issue_api:
    resource:     "@OroIssueBundle/Controller/Api/REST/IssueController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
