datagrid:
    issue-grid:
        extended_entity_name: '%oro_issue.issue.entity.class%'
        source:
            type: orm
            query:
                select:
                    - v.id
                    - v.code
                    - v.summary
                    - v.issueType
                    - CONCAT(rep.firstName, CONCAT(' ', rep.lastName)) as reporterName
                    - CONCAT(ass.firstName, CONCAT(' ', ass.lastName)) as assigneeName
                    - ip.name as issuePriority
                    - ip.label as priorityLabel
                    - ir.name as issueResolution
                    - ir.label as ResolutionLabel
                    - v.createdAt
                    - v.updatedAt
                from:
                    - { table: '%oro_issue.issue.entity.class%', alias: v }
                join:
                    left:
                        - { join: v.reporter, alias: rep }
                        - { join: v.assignee, alias: ass }
                        - { join: v.issuePriority, alias: ip }
                        - { join: v.issueResolution, alias: ir }
        inline_editing:
            enable: true
        columns:
            code:
                label: oro.issue.code.label
            summary:
                label: oro.issue.summary.label
            issueType:
                label: oro.issue.issue_type.label
            issuePriority:
                label: oro.issue.issue_priority.label
                frontend_type: select
            issueResolution:
                label: oro.issue.issue_resolution.label
                frontend_type: select
            reporterName:
                label: oro.issue.reporter.label
            assigneeName:
                label: oro.issue.assignee.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: date
            updatedAt:
                label: oro.ui.created_at
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: issue_update
                params:
                    - id
            view_link:
                type: url
                route: issue_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                code:
                    data_name: v.code
                summary:
                    data_name: v.summary
                issueType:
                    data_name: v.issue
                issuePriority:
                    data_name: ip.order
                issueResolution:
                    data_name: ir.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: v.createdAt
                updatedAt:
                    data_name: v.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: v.code
                summary:
                    type: string
                    data_name: v.summary
                issueType:
                    type: string
                    data_name: v.issueType
                issuePriority:
                    label: oro.issue.issuepriority.label
                    type: entity
                    data_name: ip.label
                    options:
                        field_options:
                            class: OroIssueBundle:IssuePriority
                            multiple: true
                            property: label
                            translatable_options: false
                issueResolution:
                    label: oro.issue.issueresolution.label
                    type: entity
                    data_name: ip.label
                    options:
                        field_options:
                            class: OroIssueBundle:IssueResolution
                            multiple: true
                            property: label
                            translatable_options: false
                reporterName:
                    type: string
                    data_name: reporterName
                assigneeName:
                    type: string
                    data_name: assigneeName
                createdAt:
                    type: date
                    data_name: v.createdAt
                updatedAt:
                    type: date
                    data_name: v.updatedAt
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye-open
                acl_resource:  oro_issue_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          edit
                acl_resource:  oro_issue_update
            delete:
                type:          delete
                label:         oro.grid.action.delete
                link:          delete_link
                icon:          remove
                acl_resource:  oro_issue_delete
    issue_user_grid:
        extends: issue-grid
        source:
            query:
                where:
                    or:
                        - v.reporter = :user_id
                        - v.assignee = :user_id
            bind_parameters:
                - user_id
        filters: ~
        options:
            toolbarOptions:
                hide: true
    subtask-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - v.parent = :parent_id
            bind_parameters:
                - parent_id
        filters: ~
        options:
            toolbarOptions:
                hide: true
    related-issues-grid:
        extends: issue-grid
        source:
             query:
                 where:
                      and:
                          - :id MEMBER OF v.issuesRelated
             bind_parameters:
                 - id
        filters: ~
        actions: ~
        options:
            toolbarOptions:
                hide: true
    collaborator-grid:
        extends: users-grid
        source:
            query:
                where:
                    and:
                        - u.id = collaborators.id
                join:
                    inner:
                        -
                            join: OroIssueBundle:Issue
                            alias: issue
                            conditionType: WITH
                            condition: "issue.id = :id"
                    left:
                        -   { join: issue.collaborators, alias: collaborators }
            bind_parameters:
                - id
        filters: ~
        actions: ~
        options:
            toolbarOptions:
                hide: true
    dashboard_user_grid:
        extends: issue-grid
        source:
            query:
                join:
                    left:
                        -
                            join: v.collaborators
                            alias: coll
                        -
                            join: v.workflowStep
                            alias: ws
                where:
                    and:
                        - coll.id = :userid
                        - ws.label <> 'Closed'

            bind_parameters:
              - userid
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
    dashboard_user_grid_full:
        extends: dashboard_user_grid
        source:
            bind_parameters:
              - userid
        options:
            toolbarOptions:
                hide: false
                pageSize: ~
