datagrid:
    issue-grid:
        extended_entity_name: '%oro_issue.issue.entity.class%'
        source:
            type: orm
            query:
                select:
                    - v.id
                    - v.code
                    - v.summary
                    - v.issueType
                    - CONCAT(rep.firstName, CONCAT(' ', rep.lastName)) as reporterName
                    - CONCAT(ass.firstName, CONCAT(' ', ass.lastName)) as assigneeName
                    - ip.name as issuePriority
                    - ip.label as priorityLabel
                    - ir.name as issueResolution
                    - ir.label as ResolutionLabel
                    - v.createdAt
                    - v.updatedAt
                from:
                    - { table: '%oro_issue.issue.entity.class%', alias: v }
                join:
                    left:
                        - { join: v.reporter, alias: rep }
                        - { join: v.assignee, alias: ass }
                        - { join: v.issuePriority, alias: ip }
                        - { join: v.issueResolution, alias: ir }
        inline_editing:
            enable: true
        columns:
            code:
                label: Code
            summary:
                label: Summary
            issueType:
                label: Type
            issuePriority:
                label: Priority
                frontend_type: select
            issueResolution:
                label: Resolution
                frontend_type: select
            reporterName:
                label: Reporter
            assigneeName:
                label: Assignee
            createdAt:
                label: created
                frontend_type: date
            updatedAt:
                label: updated
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: issue_update
                params:
                    - id
            view_link:
                type: url
                route: issue_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                code:
                    data_name: v.code
                summary:
                    data_name: v.summary
                issueType:
                    data_name: v.issue
                issuePriority:
                    data_name: ip.order
                issueResolution:
                    data_name: ir.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: v.createdAt
                updatedAt:
                    data_name: v.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: v.code
                createdAt:
                    type: date
                    data_name: v.createdAt
                updatedAt:
                    type: date
                    data_name: v.updatedAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  oro_issue_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  oro_issue_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          remove
                acl_resource:  oro_issue_delete
    issue_user_grid:
        extends: issue-grid
        source:
            query:
                where:
                    or:
                        - v.reporter = :user_id
                        - v.assignee = :user_id
            bind_parameters:
                - user_id
        filters: ~
        options:
            toolbarOptions:
                hide: true
    subtask-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - v.parent = :parent_id
            bind_parameters:
                - parent_id
        filters: ~
        options:
            toolbarOptions:
                hide: true
    related-issues-grid:
        extends: issue-grid
        source:
            query:
                where:
                    and:
                        - v.id IN (:ids)
            bind_parameters:
                - ids
        filters: ~
        options:
            toolbarOptions:
                hide: true
    collaborator-grid:
        extends: users-grid
        source:
            query:
                where:
                    and:
                        - u.id IN (:ids)
            bind_parameters:
                - ids
        filters: ~
        options:
            toolbarOptions:
                hide: true
    dashboard_user_grid:
        extends: issue-grid
        source:
            query:
                join:
                    left:
                        -
                            join: v.collaborators
                            alias: coll
                        -
                            join: v.workflowStep
                            alias: ws
                where:
                    and:
                        - coll.id = :userid
                        - ws.label <> 'Closed'

            bind_parameters:
              - userid
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
    dashboard_user_grid_full:
        extends: dashboard_user_grid
        source:
            bind_parameters:
              - userid
        options:
            toolbarOptions:
                hide: false
                pageSize: ~
