parameters:
    oro_issue.issue.form.type.issue.class: Oro\Bundle\IssueBundle\Form\Type\IssueType
    oro_issue.issue.form.handler.issue.class: Oro\Bundle\IssueBundle\Form\Handler\IssueHandler


services:
    oro_issue.form.issue:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_issue_issue_form", "oro_issue_issue"]

    oro_issue.form.handler.issue:
        class: %oro_issue.issue.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_issue.form.issue
            - @request
            - @doctrine.orm.entity_manager

    oro_issue.form.type.issue:
        class: %oro_issue.issue.form.type.issue.class%
        arguments: ['%oro_issue.issue_types%']
        tags:
            - { name: form.type, alias: oro_issue_issue }
