parameters:
    issue.importexport.class: Oro\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture

services:
    oro_issue.importexport.template_fixture.issue:
        class: '%issue.importexport.class%'
        tags:
            - { name: oro_importexport.template_fixture }

    oro_issue.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    oro_issue.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    oro_issue.importexport.processor.export_template.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@oro_issue.importexport.template_fixture.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%oro_issue.issue.entity.class%', alias: oro_issue_template }

    oro_issue.importexport.processor.export.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
             - [setDataConverter, ['@oro_issue.importexport.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%oro_issue.issue.entity.class%', alias: oro_issue_export }

    # Strategy
    oro_issue.importexport.strategy.issue.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    oro_issue.importexport.processor.import.issue:
        parent: oro_importexport.processor.import_abstract
        calls:
          - [setDataConverter, ['@oro_issue.importexport.data_converter.issue']]
          - [setStrategy, ['@oro_issue.importexport.strategy.issue.add_or_replace']]
        tags:
          - { name: oro_importexport.processor, type: import, entity: '%oro_issue.issue.entity.class%', alias: oro_issue_import }
          - { name: oro_importexport.processor, type: import_validation, entity: '%oro_issue.issue.entity.class%', alias: oro_issue_import }
