oro_menu_config:
    items:
        issue_tab:
            label: oro.issue.nav_item
            uri:   issue
            extras:
                position: 300

    tree:
        application_menu:
            children:
                issue_tab:
                    children:
