placeholders:
    view_pageActions_before:
        items:
            oro_add_issue_button:
                order: 50
    view_content_data_additional_information:
        items:
            oro_user_issues: ~

items:
    oro_user_issues:
        template: OroIssueBundle:Issue:issues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: oro_issue_view
    oro_add_issue_button:
        template: OroIssueBundle:Issue:addButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: oro_issue_create
