definitions:
    oro_issue_collaborator:
        label: 'Issue Collaborator Definition'
        enabled: true
        entity: Oro\Bundle\IssueBundle\Entity\Issue
        order: 150
        actions_configuration:
            - @call_method:
                parameters:
                    object: $.data
                    method: addCollaborator
                    method_parameters: [$.data.reporter]
            - @call_method:
                parameters:
                    object: $.data
                    method: addCollaborator
                    method_parameters: [$.data.assignee]
    oro_note_collaborator:
        label: 'Note Collaborator Definition'
        enabled: true
        entity: Oro\Bundle\NoteBundle\Entity\Note
        order: 200
        actions_configuration:
            - @call_method:
                conditions:
                    @equal: [$.data.target.class, 'Oro\Bundle\IssueBundle\Entity\Issue']
                parameters:
                    object: $.data.target
                    method: addCollaborator
                    method_parameters: [$.data.owner]
triggers:
    oro_issue_collaborator:
        -
            event: create
        -
            event: update
            field: assignee
        -
            event: update
            field: reporter
    oro_note_collaborator:
        -
            event: create