Oro\Bundle\IssueBundle\Entity\Issue:
    alias:                          issue
    title_fields:                   [summary]
    route:
        name:                       issue_view
        parameters:
            id:                     id
    search_template:                OroIssueBundle:Search:result.html.twig
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   code
            target_type:            text
            target_fields:          [code]
        -
            name:                   issueType
            target_type:            text
            target_fields:          [issueType]
        -
            name:                   issuePriority
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           label
                    target_type:    text
                    target_fields:  [priority, all_data]
        -
            name:                    workflowStep
            relation_type:           many-to-one
            relation_fields:
                -
                    name:           label
                    target_type:    text
                    target_fields:  [workflowStep, all_data]
        -
            name:                   issueResolution
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           label
                    target_type:    text
                    target_fields:  [issueResolution, all_data]
        -
            name:                   reporter
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           firstName
                    target_type:    text
                    target_fields:  [firstName, all_data]
                -
                    name:           lastName
                    target_type:    text
                    target_fields:  [lastName, all_data]
        -
            name:                   assignee
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           firstName
                    target_type:    text
                    target_fields:  [firstName, all_data]
                -
                    name:           lastName
                    target_type:    text
                    target_fields:  [lastName, all_data]