parameters:
    oro_issue.issue.entity.class: Oro\Bundle\IssueBundle\Entity\Issue
    oro_issue.issue.manager.class:  Oro\Bundle\IssueBundle\Entity\IssueManager
    oro_issue.issue.manager.api.class:  Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_issue.subscriber.issue_listener.class: Oro\Bundle\IssueBundle\EventListener\IssueListener

    oro_issue.issue_types:
        Bug: Bug
        Task: Task
        Subtask: Subtask
        Story: Story

services:
    oro_issue.issue.manager:
        class: %oro_issue.issue.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %oro_issue.issue.entity.class%
            - @router
    oro_issue.issue.manager.api:
        class: %oro_issue.issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_issue.issue.entity.class%
            - @doctrine.orm.entity_manager
    oro_issue.subscriber.issue_listener:
            class: %oro_issue.subscriber.issue_listener.class%
            arguments:
                - @service_container
            tags:
                - { name: doctrine.event_listener, event: postPersist }



